version: '3.8'
services:
  sg-dev-db:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wimagda
      POSTGRES_DB: startgood
    networks:
      - startgood
networks:
  startgood:
  